### ISSUE TITLE
problem test should support structs as solutions

### ISSUE THREAD

**Issue by masters3d** [exercism/xswift#22]

**Comment by kytrinyx** [comment]
Would you elaborate a bit please? Do you mean that the tests should allow for a wider arrange of solutions?

**Comment by masters3d** [comment]
For swift, most of the standard types are now value types and not classes as in objc. A couple of the xtest force the solution to be a class ( I did a pull request) I think a better approach is to allow test as structs ( value type )  and classes ( reference type) instead of just requiring classes. 

more about this:
https://twitter.com/andy_matuschak

**Comment by kytrinyx** [comment]
This sounds reasonable. Could you provide a link to a blog post or some documentation that talks about this? I didn't see anything specific in Andy's twitter stream.

/cc @hankturowski

**Comment by masters3d** [comment]
http://www.objc.io/issue-16/swift-classes-vs-structs.html

asciiwwdc.com/2014/sessions/229

There are other videos that he made around the subject.

**Comment by kytrinyx** [comment]
Thanks.

Do you have a list of the swift problems that require only classes? We can open an issue for each of them.

**Comment by masters3d** [comment]
grade-school/GradeSchoolTest.swift
nucleotide-count/NucleotideCountTest.swift
 robot-name/RobotNameTest.swift

**Comment by hankturowski** [comment]
It is correct that value types are preferred over reference types. Changing the let introducers in the tests to var should take care of the issue. I tested it with GradeSchool and it worked just fine. The example.swift file can stay like it is as that's not seen by the user.

@masters3d, would you like to make the change and submit a pull request? I can take care of it, but if you've already made the changes, I'll be happy to take the request.

**Comment by hankturowski** [comment]
To elaborate, the issue here is that the objects under test in the unit tests were created with the let introducer, which creates an immutable variable. For a reference type, that means that we get an immutable reference, but the class members are still mutable so things worked fine for classes. For a value type, the entire object becomes immutable so the tests will fail for structs.

Changing the let introducers to var for those objects which need to be mutable will correct the problem for GradeSchool. I haven't tested the others, but I'm assuming it's the same issue.

We should probably audit the rest of the tests to look for similar issues.

This is an odd case where two best practices are in conflict. It's best to use immutable objects when you can, and best to use value types when you can, but here are some cases where we can't do both.

**Comment by hankturowski** [comment]
@masters3d I've merged your pull request. Thanks for the help!

**Comment by masters3d** [comment]
Cool. Thank you for the problems!
