### ISSUE TITLE
Is gigasecond taking into account daylight savings time?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xswift#24]
In https://github.com/exercism/x-common/pull/44 @masters3d submitted a fix to account for daylight savings time, but since not all locales have daylight savings time, I'd rather ignore that aspect of the problem.

Can someone confirm whether or not the swift Gigasecond problem takes the daylight savings into account?

**Comment by masters3d** [comment]
Some background on this. 
http://stackoverflow.com/questions/28094757/why-is-date-datebyaddingtimeintervalseconds-off-by-1-hour

Most implementations of Gigasecond on other language tracks don't check for seconds and only check the date so the issue would not be noticeable since the hour difference would not be noticed. 

I think It doesn't take into account daylight savings anymore while it checking seconds. I'd love it if somebody double checks this for me. Thanks!!

https://github.com/exercism/xswift/pull/23/files

**Comment by kytrinyx** [comment]
> Most implementations of Gigasecond on other language tracks don't check for seconds and only check the date so the issue would not be noticeable since the hour difference would not be noticed.

We should fix that, I'll submit issues to all the tracks that implement gigasecond to suggest that we use exact times as inputs instead of dates.

**Comment by kytrinyx** [comment]
I've added an issue to each of the languages that has this problem.

**Comment by masters3d** [comment]
https://github.com/exercism/xswift/issues/32

**Comment by kytrinyx** [comment]
Thanks!
