### ISSUE TITLE
Add helpful information to the SETUP.md

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xswift#31]
The contents of the SETUP.md file gets included in
the README.md that gets delivered when a user runs the `exercism fetch`
command from their terminal.

At the very minimum, it should contain a link to the relevant
language-specific documentation on
[help.exercism.io](http://help.exercism.io).

It would also be useful to explain in a generic way how to run the tests.
Remember that this file will be included with _all_ the problems, so it gets
confusing if we refer to specific problems or files.

Some languages have very particular needs in terms of the solution: nested
directories, specific files, etc. If this is the case here, then it would be
useful to explain what is expected.

------

Thanks, @tejasbubane for suggesting that we add this documentation everywhere.
See [exercism.io#2198](https://github.com/exercism/exercism.io/issues/2198).

**Comment by kevinvanderlugt** [comment]
I think @masters3d added the basic information in c9ae5bcf0476e8eab0d3da957ffc6de79c2a18b4

I have a slightly different way of running the test that I find to be easier.  Instead of creating one xCode project for each exercise, I have one generic exercism xCode project.  Then I just need to drag in the newest exercise, create the new file for the solution and add that to the Tests target.   

Curious how everyone else does it since it seemed like the original setup was a lot of extra overhead when I got started.  Maybe this should be discussed in a different issue though?

**Comment by masters3d** [comment]
I think using IOS as the test bed is the most straightforward way. (maybe not the fastest)
But if you have suggestions on changes see the docs repo
https://github.com/exercism/docs/blob/master/app/pages/languages/getting-started-with-swift.md

A lot of issues could be introduced when you start to mix multiple projects. For example. You cant have files with the same name in one xcode project. 

I personally just use an osx project since those build faster for me but that can get confusing when people see something like this and accidentally click yes.
![image](https://cloud.githubusercontent.com/assets/6539412/6830380/ab833b74-d2d6-11e4-8218-117605b89d19.png)

**Comment by kevinvanderlugt** [comment]
Yeah, I suppose I can see how having all the tests in one project could get confusing if you wanted to name your solution the same as a file that already exists.  
Usually I end up naming it the name of the class that is going to be tested though.   Or if it's an extension I add the in the filename what is getting added to the class.

I will have to give an osx project a try since ios projects always open the simulator.
Eitherway, I think this issue can be closed with your commit earlier?
