### ISSUE TITLE
Example files naming and Xcode Project

### ISSUE THREAD

**Issue by masters3d** [exercism/xswift#42]
exercism/xruby#102
"The only restriction is that the example file needs to have /[Ee]xample/ in the name" - @kytrinyx

I want to understand why the test files can be different names but the examples files names need to be "/[Ee]xample/ ". In an xcode project I can't have the same filename for different files in the same project because the project wont compile. Having all the problems in one project would allow faster updates of language changes ( 1.x to 1.x+ ) and in the future Travis integration.

http://docs.travis-ci.com/user/osx-ci-environment/
http://docs.travis-ci.com/user/languages/objective-c/
![image](https://cloud.githubusercontent.com/assets/6539412/7061031/8dd33e7e-de40-11e4-9abe-b1511aca2455.png)
https://github.com/exercism/exercism.io/issues/316

**Comment by masters3d** [comment]
Maybe it was a little late last night for me.  Would these be  valid "example" file names?

BobExample.swift
LeapExample.swift
etc

**Comment by hankturowski** [comment]
@masters3d, this is a great idea. Being able to name the tests BobTest.swift, the example BobExample.swift and the user's solution Bob.swift would really simplify things. It would not only make it easier to maintain the problem sets, but it would streamline the user's process. Instead of creating a new project for each exercise, they could just use the same project and add new exercises as they go.

If the restriction is that the examples must have /[Ee]xample/ in them, then BobExample.swift should work. That regex isn't anchored, so it should be okay. Let's get confirmation from @kytrinyx, then rename the existing example files.

**Comment by kytrinyx** [comment]
@masters3d Yepp, `BobExample.swift` and `LeapExample.swift` are fine.

Would this structure the repo differently?

**Comment by masters3d** [comment]
no, only the `example.swift` in each problem folder would be renamed as above.

**Comment by masters3d** [comment]
Thank you! renaming done.
